alias tf="tail -f"
alias dcmp="docker-compose"
alias s="sudo"
alias update="sudo apt update; sudo apt upgrade"
alias dupdate="sudo apt update; sudo apt dist-upgrade"
alias c="clear"
alias pryderi="sirpryderi"
