#!/bin/bash
echo -e "\e[94m\e[7m\e[1m    _____ _      ____                 __          _  
   / ___/(_)____/ __ \_______  ______/ /__  _____(_) 
   \__ \/ / ___/ /_/ / ___/ / / / __  / _ \/ ___/ /  
  ___/ / / /  / ____/ /  / /_/ / /_/ /  __/ /  / /   
 /____/_/_/  /_/   /_/   \__, /\__,_/\___/_/  /_/    
                        /____/                       
                                                     
                        TOOLS                        
                                                     
"

echo -e "\e[0m\e[1m\e[32mSirPryderi/tools are working! You're good to go! :)\e[0m"

echo ""

echo -e "\e[2mAvaiable commands are:\e[0m"
ls ~/tools/scripts
